services:
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_DB: murdermystery
      POSTGRES_USER: murdermystery
      POSTGRES_PASSWORD: murdermystery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
